### PR TITLE
Add support autoshutdown plugin

### PR DESCRIPTION
**Pull request by tuxgasy**
Add support for autoshutdown plugin by generate and remove tmp file.

### CODE REVIEW

**Comment by ryecoaaron** [comment]
Why not change the autoshutdown plugin to detect if borg is running?  Many borg users are probably not using autoshutdown (I'm not) and this is a pointless semaphore file in those cases.  I realize it doesn't hurt anything but I'm not excited about maintaining something in the borg plugin for autoshutdown.

**Comment by tuxgasy** [comment]
I was inspired by some official plugins (like rsync or usbbackup) that implement a runfile.
Anyway, thank you for your feedback and for this very useful plugin.

**Comment by ryecoaaron** [comment]
I'm not saying no.  Just looking for some justification.  usbbackup probably uses it to keep more than one job from running.  I don't see it for rsync.

**Comment by tuxgasy** [comment]
You can see this [template](https://github.com/openmediavault/openmediavault/blob/5.x/deb/openmediavault/srv/salt/omv/deploy/rsync/files/cron-rsync-script.j2) for rsync.
The runfile is used to avoid multiple launch. I think that the initial goal is not for autoshutdown plugin.

**Comment by ryecoaaron** [comment]
@nrandon, which plugin do you think this belongs in?  I don't know enough about autoshutdown to determine this.  If this is added to the borg plugin, it seems it should go in others as well (backup, rsnapshot, snapraid, etc).  If there is an easy way to add support in the autoshutdown plugin that only needs to be maintained in one place, that would be nice.

**Comment by nrandon** [comment]
@ryecoaaron I looked into this and you still need to add a plugin to Autoshutdown to get this two work as like the example give here: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/tree/master/etc/autoshutdown.d. However I not sure you need to do any of this, can you not just add/set 'borg' to 'TEMPPROCNAMES' (can be set in the GUI) to detect if the borg executable is running, as this is what the setting is meant to do?

**Comment by ryecoaaron** [comment]
@tuxgasy Would you be able to test if adding borg to TEMPPROCNAMES works?  This seems easier to maintain.

**Comment by tuxgasy** [comment]
I test TEMPROCNAMES and it works.
Thank you.

**Comment by ryecoaaron** [comment]
@tuxgasy Do you still feel this change should be made to the borg plugin then?

**Comment by tuxgasy** [comment]
In the context of my use, TEMPROCNAMES is enough for me.

**Pull request closed without merging**
